/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme.ts
 * Command: astryx theme build lib/theme.ts
 * Generated: 2026-08-01T20:35:52.900Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
