/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib\theme.ts
 * Command: astryx theme build lib\theme.ts
 * Generated: 2026-09-02T19:30:23.858Z
 */

/// <reference path="./legalos.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const legalosTheme: DefinedTheme;
