"""Expenses — the disbursements half of a matter's billable activity.

Court fees, filing fees, expert retainers, translation and travel are advanced
by the firm and recovered from the client on an invoice exactly the way time
is. The lifecycle therefore mirrors time_entries.py: an expense is recoverable
until billing.py stamps its invoice_id, after which it is frozen and excluded
from the next invoice.

The row's `amount` is generated by the database from quantity and unit_amount,
so it is never written by this module.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal

import psycopg

from legalrag.practice import NotFoundError, fetch_all, fetch_one

CATEGORIES = (
    "court_fees", "filing", "expert", "travel", "translation", "courier", "other",
)

_COLUMNS = """
    e.id, e.organization_id, e.matter_id, m.name AS matter_name,
    e.clerk_user_id, e.entry_date, e.description, e.category, e.quantity,
    e.unit_amount, e.amount, e.billable, e.currency, e.invoice_id, e.created_at
"""


@dataclass
class Expense:
    id: int
    organization_id: int
    matter_id: int
    matter_name: str
    clerk_user_id: str
    entry_date: date
    description: str
    category: str
    quantity: Decimal
    unit_amount: Decimal
    amount: Decimal
    billable: bool
    currency: str
    invoice_id: int | None
    created_at: datetime


def list_expenses(
    conn: psycopg.Connection,
    organization_id: int,
    *,
    matter_id: int | None = None,
    clerk_user_id: str | None = None,
    since: date | None = None,
    until: date | None = None,
    unbilled_only: bool = False,
) -> list[Expense]:
    sql = (
        f"SELECT {_COLUMNS} FROM expenses e JOIN matters m ON m.id = e.matter_id "
        "WHERE e.organization_id = %s"
    )
    params: list[object] = [organization_id]
    if matter_id is not None:
        sql += " AND e.matter_id = %s"
        params.append(matter_id)
    if clerk_user_id:
        sql += " AND e.clerk_user_id = %s"
        params.append(clerk_user_id)
    if since:
        sql += " AND e.entry_date >= %s"
        params.append(since)
    if until:
        sql += " AND e.entry_date <= %s"
        params.append(until)
    if unbilled_only:
        sql += " AND e.invoice_id IS NULL AND e.billable"
    sql += " ORDER BY e.entry_date DESC, e.id DESC"
    return fetch_all(conn, Expense, sql, tuple(params))


def get_expense(
    conn: psycopg.Connection, organization_id: int, expense_id: int
) -> Expense | None:
    return fetch_one(
        conn,
        Expense,
        f"SELECT {_COLUMNS} FROM expenses e JOIN matters m ON m.id = e.matter_id "
        "WHERE e.organization_id = %s AND e.id = %s",
        (organization_id, expense_id),
    )


def create_expense(
    conn: psycopg.Connection,
    organization_id: int,
    *,
    matter_id: int,
    clerk_user_id: str,
    entry_date: date,
    unit_amount: Decimal,
    quantity: Decimal = Decimal(1),
    description: str = "",
    category: str = "other",
    billable: bool = True,
    currency: str = "EGP",
) -> Expense:
    if category not in CATEGORIES:
        raise ValueError(f"invalid category {category!r}")
    if quantity <= 0:
        raise ValueError("quantity must be greater than zero")
    if unit_amount < 0:
        raise ValueError("unit_amount cannot be negative")
    with conn.cursor() as cur:
        cur.execute(
            "SELECT 1 FROM matters WHERE organization_id = %s AND id = %s",
            (organization_id, matter_id),
        )
        if cur.fetchone() is None:
            raise NotFoundError(f"matter {matter_id}")
        cur.execute(
            "INSERT INTO expenses (organization_id, matter_id, clerk_user_id, "
            "entry_date, description, category, quantity, unit_amount, billable, "
            "currency) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
            (
                organization_id, matter_id, clerk_user_id, entry_date, description,
                category, quantity, unit_amount, billable, currency,
            ),
        )
        expense_id = cur.fetchone()[0]
    conn.commit()
    expense = get_expense(conn, organization_id, expense_id)
    assert expense is not None
    return expense


_UPDATABLE = {
    "matter_id", "entry_date", "description", "category", "quantity",
    "unit_amount", "billable",
}


def update_expense(
    conn: psycopg.Connection, organization_id: int, expense_id: int, **changes
) -> Expense:
    fields = {k: v for k, v in changes.items() if k in _UPDATABLE and v is not None}
    if "category" in fields and fields["category"] not in CATEGORIES:
        raise ValueError(f"invalid category {fields['category']!r}")
    if "quantity" in fields and fields["quantity"] <= 0:
        raise ValueError("quantity must be greater than zero")
    if "unit_amount" in fields and fields["unit_amount"] < 0:
        raise ValueError("unit_amount cannot be negative")
    if fields:
        assignments = ", ".join(f"{name} = %s" for name in fields)
        with conn.cursor() as cur:
            # An expense already on an invoice is frozen, for the same reason a
            # billed time entry is: the client has been sent the total.
            cur.execute(
                f"UPDATE expenses SET {assignments} "
                "WHERE organization_id = %s AND id = %s AND invoice_id IS NULL",
                (*fields.values(), organization_id, expense_id),
            )
            if cur.rowcount == 0:
                raise NotFoundError(f"unbilled expense {expense_id}")
        conn.commit()
    expense = get_expense(conn, organization_id, expense_id)
    if expense is None:
        raise NotFoundError(f"expense {expense_id}")
    return expense


def delete_expense(
    conn: psycopg.Connection, organization_id: int, expense_id: int
) -> None:
    with conn.cursor() as cur:
        cur.execute(
            "DELETE FROM expenses "
            "WHERE organization_id = %s AND id = %s AND invoice_id IS NULL",
            (organization_id, expense_id),
        )
        if cur.rowcount == 0:
            raise NotFoundError(f"unbilled expense {expense_id}")
    conn.commit()


@dataclass
class ExpenseSummary:
    total_amount: Decimal
    billable_amount: Decimal
    unbilled_amount: Decimal


def summarize(
    conn: psycopg.Connection,
    organization_id: int,
    *,
    matter_id: int | None = None,
    since: date | None = None,
    until: date | None = None,
) -> ExpenseSummary:
    sql = """
        SELECT coalesce(sum(amount), 0),
               coalesce(sum(amount) FILTER (WHERE billable), 0),
               coalesce(sum(amount) FILTER (WHERE billable
                        AND invoice_id IS NULL), 0)
          FROM expenses WHERE organization_id = %s
    """
    params: list[object] = [organization_id]
    if matter_id is not None:
        sql += " AND matter_id = %s"
        params.append(matter_id)
    if since:
        sql += " AND entry_date >= %s"
        params.append(since)
    if until:
        sql += " AND entry_date <= %s"
        params.append(until)
    with conn.cursor() as cur:
        cur.execute(sql, tuple(params))
        return ExpenseSummary(*cur.fetchone())
