#!/usr/bin/env python3
"""
توليد ملف رموز CSS المشترك لهوية «السِّجل» (sijil-tokens.css)
انطلاقاً من مصدر الحقيقة الواحد: `web/lib/theme.ts`.

الاستخدام:
    python marketing/scripts/build-tokens.py          # توليد الملف
    python marketing/scripts/build-tokens.py --check  # التحقق من التطابق دون كتابة
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
THEME_TS = REPO_ROOT / "web" / "lib" / "theme.ts"
OUT_CSS = REPO_ROOT / "marketing" / "assets" / "css" / "sijil-tokens.css"


def parse_theme_ts(ts_path: pathlib.Path) -> tuple[dict[str, str], dict[str, str]]:
    """استخراج رموز الثيمين الفاتح والداكن من web/lib/theme.ts."""
    content = ts_path.read_text(encoding="utf-8")
    match = re.search(r"const sijilTokens:\s*SijilThemeTokens\s*=\s*\{([\s\S]+?)\n\};", content)
    if not match:
        raise ValueError("لم يتم العثور على كائن sijilTokens داخل web/lib/theme.ts")

    block = match.group(1)

    light_tokens: dict[str, str] = {}
    dark_tokens: dict[str, str] = {}

    # 1. مطابقة المتغيرات ذات القيم الزوجية [فاتح, داكن]
    tuple_pattern = re.compile(
        r'["\'](--[a-zA-Z0-9_-]+)["\']:\s*\[\s*["\']([^"\']+)["\'],\s*["\']([^"\']+)["\'],?\s*\]',
        re.MULTILINE | re.DOTALL,
    )
    for m in tuple_pattern.finditer(block):
        name, light_val, dark_val = m.groups()
        light_tokens[name] = light_val
        dark_tokens[name] = dark_val

    # 2. مطابقة المتغيرات ذات القيمة الفردية (تسري على الثيمين)
    single_pattern = re.compile(r'["\'](--[a-zA-Z0-9_-]+)["\']:\s*["\']([^"\']+)["\']')
    for m in single_pattern.finditer(block):
        name, val = m.groups()
        if name not in light_tokens:
            light_tokens[name] = val
            dark_tokens[name] = val

    # الظلال الخاصة بالقالب
    light_tokens["--shadow"] = "0 1px 2px rgba(18, 22, 34, 0.05), 0 10px 26px -14px rgba(18, 22, 34, 0.16)"
    light_tokens["--shadow-lg"] = "0 2px 6px rgba(18, 22, 34, 0.06), 0 24px 60px -20px rgba(18, 22, 34, 0.28)"

    dark_tokens["--shadow"] = "0 1px 2px rgba(0, 0, 0, 0.3), 0 10px 26px -14px rgba(0, 0, 0, 0.6)"
    dark_tokens["--shadow-lg"] = "0 2px 8px rgba(0, 0, 0, 0.4), 0 28px 64px -20px rgba(0, 0, 0, 0.75)"

    return light_tokens, dark_tokens


def generate_css(light_tokens: dict[str, str], dark_tokens: dict[str, str]) -> str:
    """توليد محتوى ملف CSS المنظم."""
    ordered_keys = [
        "--brand-h",
        "--r",
        "--rs",
        "--rowpad",
        "--bg",
        "--surface",
        "--surface2",
        "--surface3",
        "--border",
        "--border2",
        "--text",
        "--text2",
        "--text3",
        "--primary",
        "--primary-h",
        "--primary-fg",
        "--primary-soft",
        "--accent",
        "--accent-fg",
        "--accent-soft",
        "--success",
        "--success-soft",
        "--warn",
        "--warn-soft",
        "--danger",
        "--danger-soft",
        "--info",
        "--info-soft",
        "--shadow",
        "--shadow-lg",
        "--ring",
    ]

    lines = [
        "/**",
        " * @generated from web/lib/theme.ts — do not edit manually.",
        " * Single Source of Truth for Sijil design tokens (T-048 / T-055 / E-5).",
        " * Generated by `python marketing/scripts/build-tokens.py`.",
        " */",
        "",
        ":root,",
        '[data-theme="light"] {',
        "  color-scheme: light;",
    ]

    for k in ordered_keys:
        if k in light_tokens:
            lines.append(f"  {k}: {light_tokens[k]};")

    lines.extend([
        "}",
        "",
        '[data-theme="dark"] {',
        "  color-scheme: dark;",
    ])

    for k in ordered_keys:
        if k in dark_tokens:
            lines.append(f"  {k}: {dark_tokens[k]};")

    lines.extend([
        "}",
        "",
    ])

    return "\n".join(lines)


def main() -> int:
    check_mode = "--check" in sys.argv

    if not THEME_TS.exists():
        print(f"خطأ: مصدر الرموز غير موجود: {THEME_TS}", file=sys.stderr)
        return 1

    light, dark = parse_theme_ts(THEME_TS)
    generated = generate_css(light, dark)

    if check_mode:
        if not OUT_CSS.exists():
            print(f"build-tokens: {OUT_CSS.name} غير موجود — شغّل build-tokens.py أولاً")
            return 1
        current = OUT_CSS.read_text(encoding="utf-8")
        if current.strip() != generated.strip():
            print("build-tokens: ملف الرموز متأخر أو غير متطابق — شغّل build-tokens.py")
            return 1
        print("build-tokens: رموز CSS متطابقة 100% مع theme.ts")
        return 0

    OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
    OUT_CSS.write_text(generated, encoding="utf-8")
    print(f"build-tokens: تم توليد {OUT_CSS.relative_to(REPO_ROOT)} بنجاح من {THEME_TS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
