#!/usr/bin/env python3
"""Outline the alsigil wordmark from Archivo and emit lib/brand/marks.ts.

The identity sheet sets the wordmark in Archivo 600 at -5% tracking. Shipping
that as live text would make the mark depend on a webfont: the wrong face
during load, a different face if the font 404s, and no mark at all inside an
SVG favicon (where no @font-face applies). So the wordmark is outlined once,
here, and shipped as path data -- artwork, which is what a wordmark is.

Run:  uv run --with fonttools --with uharfbuzz scripts/brand/build-marks.py
      (or any venv with fonttools + uharfbuzz on the path)

Requires network on first run to fetch the upstream font.
"""
from __future__ import annotations

import pathlib
import urllib.request

import uharfbuzz as hb
from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

# Archivo is OFL. Pinned to the upstream repo rather than the Google Fonts CSS
# API so the bytes are the full font, not a latin subset with hinting stripped.
FONT_URL = (
    "https://raw.githubusercontent.com/google/fonts/main/ofl/archivo/"
    "Archivo%5Bwdth,wght%5D.ttf"
)
WEIGHT = 600
WIDTH = 100
TRACKING = -0.05  # -5%, per the identity sheet

HERE = pathlib.Path(__file__).resolve().parent
CACHE = HERE / ".cache"
OUT = HERE.parent.parent / "lib" / "brand" / "marks.ts"


def load_font() -> TTFont:
    CACHE.mkdir(exist_ok=True)
    src = CACHE / "Archivo-VF.ttf"
    if not src.exists():
        urllib.request.urlretrieve(FONT_URL, src)
    instance = instantiateVariableFont(
        TTFont(src), {"wght": WEIGHT, "wdth": WIDTH}, inplace=False
    )
    dst = CACHE / f"Archivo-{WEIGHT}.ttf"
    instance.save(dst)
    return instance, dst


def outline(font: TTFont, path: pathlib.Path, text: str) -> dict:
    """Shape `text` and return its outline as one SVG path on the baseline."""
    upem = font["head"].unitsPerEm
    glyphs = font.getGlyphSet()
    names = font.getGlyphOrder()

    # HarfBuzz rather than raw advance widths: GPOS kerning is what a browser
    # would apply, and the outlined mark has to match what the design doc shows.
    with open(path, "rb") as fh:
        hbfont = hb.Font(hb.Face(hb.Blob(fh.read())))
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf)

    track = TRACKING * upem
    commands: list[str] = []
    bounds = BoundsPen(glyphs)
    x = 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        name = names[info.codepoint]
        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.0f}")
        # SVG's y axis points down; flip the outline so the baseline is y=0.
        glyphs[name].draw(TransformPen(pen, Transform(1, 0, 0, -1, x + pos.x_offset, 0)))
        glyphs[name].draw(TransformPen(bounds, Transform(1, 0, 0, -1, x + pos.x_offset, 0)))
        commands.append(pen.getCommands())
        x += pos.x_advance + track

    xmin, ymin, xmax, ymax = bounds.bounds
    return {
        "path": " ".join(commands),
        # Trailing tracking is space after the last letter, not part of the mark.
        "advance": (x - track) / upem,
        "left": xmin / upem,
        "right": xmax / upem,
        "top": ymin / upem,
        "bottom": ymax / upem,
    }


def ts_mark(name: str, text: str, m: dict) -> str:
    return f"""
/** `{text}` — Archivo {WEIGHT}, {TRACKING:+.0%} tracking, outlined.
 *  Baseline at y=0, pen origin at x=0, in a 1000-unit em. */
export const {name}: OutlinedMark = {{
  path: "{m['path']}",
  advance: {m['advance']:.4f},
  ink: {{ left: {m['left']:.4f}, right: {m['right']:.4f}, top: {m['top']:.4f}, bottom: {m['bottom']:.4f} }},
}};
"""


def main() -> None:
    font, path = load_font()
    marks = {
        "WORDMARK": "alsigil",
        "MONOGRAM": "al",
        "INITIAL": "a",
    }
    body = "".join(ts_mark(name, text, outline(font, path, text)) for name, text in marks.items())

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"""// GENERATED by scripts/brand/build-marks.py — do not edit by hand.
// Source: Archivo (OFL) variable font, instanced at wght={WEIGHT} wdth={WIDTH},
// shaped with HarfBuzz, tracked {TRACKING:+.0%}. Re-run the script to change any of that.

/** An outlined string: path data in a 1000-unit em with the baseline at y=0
 *  and the pen origin at x=0, plus the metrics needed to place it.
 *  `advance` is the typographic width (what the next glyph would start at);
 *  `ink` is the tight bounding box of the drawn shape, which is what you
 *  measure a logo by. Both are in em units. */
export type OutlinedMark = {{
  path: string;
  advance: number;
  ink: {{ left: number; right: number; top: number; bottom: number }};
}};
{body}""",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
